### ISSUE TITLE
Composer errors

### ISSUE THREAD

**Issue by zs-sz** [IconoCoders/OTPSimplePay-Magento2#1]
Hi there,

Do I need to do something special apart from adding the namespaces to composer.json? I keep getting an error, no matter what I do. 

- if I use require from the commandline the sdk zipball fails to download 
- if I add it through composer.json and run update it fails on minimum stability even if I set the min-req to dev

EDIT: could you show me an example composer.json perhaps?

Thnx

**Comment by progcode** [comment]
Hello @zs-sz, I will investigate this issue. Thanks!

**Comment by zs-sz** [comment]
I just realized that the otp-simple-sdk is not on your account anymore... google still shows it in search results but the github page comes up with a 404.

**Comment by progcode** [comment]
Yes, we will solve this issue ASAP. Thank you for your patience

**Comment by progcode** [comment]
We just fixed this issue.

https://github.com/IconoCoders/otp-simple-sdk
https://packagist.org/packages/iconocoders/otp-simple-sdk

**Comment by zs-sz** [comment]
Cool! thnx for the speedy reply
