### ISSUE TITLE
Ajánlott javítások

### ISSUE THREAD

**Issue by simieee** [IconoCoders/OTPSimplePay-Magento2#12]
namespace Iconocoders\OtpSimple\Helper -> class Data objektum calculateHash függvényébe a $this->getSecretKey() meghívásakor érdemes lenne trim()-el ellátni: trim($this->getSecretKey())

Magento 2-ben az Address esetében a lekért: $address->getStreet() tömbbel tér vissza, ezért az  SimplePay oldalán az utca nem jelenik meg, célszerű használni az implode(" ", $address->getStreet()) amennyiben tömbbel tér vissza a függvény, ha az admin belőtte, hogy az utca 1 soros, akkor stringgel tér vissza. Ez érvényes a szállítási és számlázási címre.

HTTPS esetében a namespace Iconocoders\OtpSimple\Controller\Payment\Backref.php-ban az $actualLink használatakor beégetve a http-t használni nem szabad, mert hibával elszáll a folyamat ami a frontenden egy Internal Server Error 500-at okoz.

Továbbá a Backref esetében és a szerver beállításoknak, átirányításnak köszönhetően (HTTPS miatt) a szerver és/vagy böngésző %7C karakterekből gyakorta kreált "|" jelet ami miatt ctrl hash kód és az URL-ből előállított hash kód nem egyezett meg -> Internal Server Error 500

**Comment by progcode** [comment]
Fixed #15 

https://github.com/IconoCoders/OTPSimplePay-Magento2/releases/tag/Public2.1.1
