### ISSUE TITLE
Checkout results at other payment methods

### ISSUE THREAD

**Issue by KerdiB** [IconoCoders/OTPSimplePay-Magento2#2]
The OTP Simple checkout results show up on all payment method checkout success pages.
For example when using Cash on delivery checkout is successfull it shows:

Card validation is successfully done.
SimplePay Reference Number: 
Order Identifier: 
Date:

**Comment by progcode** [comment]
Thanks @KerdiB we will investigate this issue

**Comment by pkarsai** [comment]
I have the same problem on Magento 2.2.7.

**Comment by progcode** [comment]
This is now fixed here: https://github.com/IconoCoders/OTPSimplePay-Magento2/issues/5
