### ISSUE TITLE
#ICOMG-2 Executing backref controller if plugin disabled on dashboard

### ISSUE THREAD

**Issue by vaso123** [IconoCoders/OTPSimplePay-Magento2#2]
Hi!

I am facing with the following problem:

I've checkd and in all scopes the plugin turned off on the dashboard. In config file the module is enabled.

Because not enabled in dashborad / configuration / payments, it is not an option when I go to payment methods on checkout page.

But when I push the Place order button, the `Observer/AddOrderIdToSession.php` executes run, and `view/frontend/templates/order/result.phtml` also tries  to load.

At this point, in template, the $backref variable will be emtpy what casuse undefiend index notice.

Why observers run if simple pay is not enabled as a payment method?

**Comment by progcode** [comment]
Hey @vaso123 please try version 2.3.6 (dev release)

https://packagist.org/packages/iconocoders/magento2-otp-simple-payment#2.3.6

Thanks!

**Comment by progcode** [comment]
Thank you for your feedback...

**Comment by progcode** [comment]
https://github.com/IconoCoders/OTPSimplePay-Magento2/tree/3.0.0-beta

**Comment by progcode** [comment]
Fixed in https://github.com/IconoCoders/OTPSimplePay-Magento2/releases/tag/2.3.6 && https://github.com/IconoCoders/OTPSimplePay-Magento2/releases/tag/3.0.0-beta3
