### ISSUE TITLE
Sikertelen fizetés

### ISSUE THREAD

**Issue by hypernics** [IconoCoders/OTPSimplePay-Magento2#4]
Sikertelen fizetés esetén elvész a kosár tartalma és nem lehet megismételni a fizetést. Ugyanez a paypal express esetén úgy működik, hogy visszadob a kosárhoz és lehet másik fizetési módot választani.
Itt ez nem valósítható meg?

**Comment by progcode** [comment]
Köszönjük @hypernics a bejelentést, megnézzük és mihamarabb javítjuk.

**Comment by progcode** [comment]
Szeretnék kérni egy system reportot, hogy reprodukálni tudjuk a hibát. Köszi! @hypernics

**Comment by norbertladacs** [comment]
Úgy látom, hogy az alap magento működés szerint checkoutkor a sessionből törlődik a kosár még az OTP-s fizetés előtt.

Sikertelen fizetésél a kódnak kellene visszaállítani a kosarat?

**Comment by progcode** [comment]
Nem kellene visszaallitania, hiszen ahogy irod is, ez alap mukodes. De szeretnem megerteni a problemat, amit @hypernics jelzett, ezert kertem system reportot, lehet mas modullal van conflict.

**Comment by progcode** [comment]
Fixed: https://github.com/IconoCoders/OTPSimplePay-Magento2/pull/8

**Comment by progcode** [comment]
https://github.com/IconoCoders/OTPSimplePay-Magento2/releases/tag/Public2.1.0

**Comment by progcode** [comment]
@hypernics Kerlek teszteljetek a folyamatot a kovetkezo branch-el: https://github.com/IconoCoders/OTPSimplePay-Magento2/tree/cancelled-order-fix

**Comment by hypernics** [comment]
Köszi, ránézek és visszajelzek!

**Comment by progcode** [comment]
Sikerult megnezned? @hypernics

**Comment by progcode** [comment]
Fixed #15 

https://github.com/IconoCoders/OTPSimplePay-Magento2/releases/tag/Public2.1.1
