### ISSUE TITLE
Hibajavítások

### ISSUE THREAD

**Issue by pkarsai** [IconoCoders/OTPSimplePay-Magento2#5]
Üdv,

Javítottam egy hibát, ami miatt egyes esetekben a korábbi tranzakció backref adatai újra felhasználásra kerültek. Továbbá javítottam több hibát a magyar és az angol dokumentációban.
Ha kapok hozzáférést, feltölteném a módosításokat.

Karsai Péter

**Comment by progcode** [comment]
Szia! A saját github repodból tudsz pull-requestet nyitni, ami után tudjuk mergelni a módosításokat, ha azok megfelelőek. Köszi!

**Comment by progcode** [comment]
https://github.com/IconoCoders/OTPSimplePay-Magento2/releases/tag/Public1.1

**Comment by progcode** [comment]
https://github.com/IconoCoders/OTPSimplePay-Magento2/releases/tag/Public2.1.0
